backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "announcements"
    label: "Ανακοινώσεις"
    folder: "_announcements"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Τίτλος", name: "title", widget: "string" }
      - { label: "Ημερομηνία", name: "date", widget: "datetime" }
      - { label: "Κείμενο", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Gallery"
    folder: "assets/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Εικόνα", name: "image", widget: "image" }
